name: Publish Python Package

on:
  push:
    tags:
      - "v*.*.*" # Triggers on version tags like v0.1.0, v1.2.3, etc.

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    if: github.ref == 'refs/heads/main' # Only run when tag is pushed to main branch

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # This ensures all tags are fetched
      - uses: astral-sh/setup-uv@v3
      - run: uv build
      - run: uv publish --trusted-publishing always
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
